//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaMODEPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Race()
        {
            this.Boat = new HashSet<Boat>();
        }
    
        public int RaceID { get; set; }
        public int BoatID { get; set; }
        public Nullable<int> DataID { get; set; }
        public Nullable<int> VideoID { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<int> ConversationID { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Boat> Boat { get; set; }
        public virtual Conversation Conversation { get; set; }
        public virtual Data Data { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Video Video { get; set; }
    }
}
