//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeaMODEPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class seamodeEntities3 : DbContext
    {
        public seamodeEntities3()
            : base("name=seamodeEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Boat> Boat { get; set; }
        public virtual DbSet<Conversation> Conversation { get; set; }
        public virtual DbSet<Data> Data { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Member> Member { get; set; }
        public virtual DbSet<Picture> Picture { get; set; }
        public virtual DbSet<Training> Training { get; set; }
        public virtual DbSet<Video> Video { get; set; }
        public virtual DbSet<Race> Race { get; set; }
    }
}
